### ISSUE TITLE
Waiting for an asynchronous Request from server

### ISSUE THREAD

**Issue by mambap** [embeddedmz/httpclient-cpp#9]
Hello, 
I'm currently building a http client using this project. I want to make an instance httpclient-cpp waiting for an asynchronous request from a server.

**Comment by embeddedmz** [comment]
Hello mambap,

If I understand correctly, you want to create an HTTP server ? for this you can use Microsoft C++ REST SDK, it's a cross platorm library. You can also take a look at this example : https://github.com/embeddedmz/CppRestServerExample

A client is always the one that starts a session, then the server responds ! The server never asks first (normal, it's a server).

There's also other libraries, the principle is always the same, for some HTTP verbs (POST, GET, PUT, DEL, etc...) you define some callbacks that will be called when an http client requests something from your HTTP server.

The CPP-REST SDK is a good library since it also has JSON support which is commonly used to describe data in REST APIs. The only drawback is that you need to have the nasty Boost libraries (and possibly OpenSSL for secure HTTP) installed.

Don't forget to use locks if your data sources are updated in another threads, the callbacks are called from other threads by CPP-REST.

Hope that helps.

Regards.

**Comment by embeddedmz** [comment]
There's also Websockets, an alternative to HTTP REST that avoids the REQUEST-REPLY pattern since the server can send data to the client at any time and without requiring the client to send periodically requests and it's more appropriate for real time applicaitons.

Look at these Qt examples : https://doc.qt.io/qt-5/qtwebsockets-examples.html with a web browser you can communicate with a C++/QT program like using classic TCP sockets.
